[default.general]
chip = "STM32H747XIHx"
connect_under_reset = false

[default.probe]
protocol = "Swd"

[default.flashing]
enabled = true
restore_unwritten_bytes = false
do_chip_erase = false

[default.reset]
enabled = true
halt_afterwards = false

[default.rtt]
enabled = true